# Generated by Django 4.2.5 on 2023-09-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='loacation',
            new_name='location',
        ),
    ]
