# Generated by Django 4.2.5 on 2023-09-24 12:15

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_category_alter_review_book_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ASCdfghijkl167239', length=22, max_length=40, prefix='book=?', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ASCdfghijkl167239', length=22, max_length=40, prefix='category=?', unique=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ASCdfghijkl167239', length=22, max_length=40, prefix='progress=?', unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ASCdfghijkl167239', length=22, max_length=40, prefix='review=?', unique=True),
        ),
    ]
